# HemOnc Bundle Validation

This notebook is for live validation of SCOOP's HemOnc-backed regimen selection.

It is designed to help inspect:

- variant-backed query entries
- non-variant `bundle_recipe` entries
- compiled SQL for each phase
- raw phase matches from the HemOnc database
- final assembled bundle candidates

Set `HEMONC_ENGINE_URL` in your environment before running the execution cells.

In [1]:
from pathlib import Path
import os
import sys

import pandas as pd
import sqlalchemy as sa
import sqlalchemy.orm as so
from IPython.display import Markdown, display


def find_repo_root(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    for candidate in (current, *current.parents):
        if (candidate / "scoop").exists() and (candidate / "notebooks").exists():
            return candidate
    raise RuntimeError("Could not locate the SCOOP repo root.")


ROOT = find_repo_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

CONFIG_ROOT = ROOT / "scoop" / "configuration"

from scoop.configuration.config_loader import load_profile_manifest
from scoop.configuration.regimen_registry import load_regimen_registry
from scoop.utils.hemonc_query import (
    apply_default_component_requirements,
    build_variant_query_artifacts,
    execute_variant_query,
)
from scoop.utils.hemonc_bundle import (
    build_bundle_query_artifacts_for_entry,
    execute_bundle_query_for_entry,
)

2026-04-07 21:49:44,318 | DEBUG   | scoop | SCOOP logging initialized

In [2]:
PROFILE_ID = "nsclc"
HEMONC_ENGINE_URL = "postgresql+psycopg2://hemonc_user:hemonc_password@localhost:5555/hemonc_db"

manifest = load_profile_manifest(PROFILE_ID, base_dir=CONFIG_ROOT)
REGISTRY_PATH = CONFIG_ROOT / "profiles" / PROFILE_ID / manifest.regimen_registry
REGISTRY_MODEL = load_regimen_registry(REGISTRY_PATH)

manifest

ProfileManifest(profile_id='nsclc', default_graph='nsclc', graphs={'nsclc': PosixPath('nsclc.yaml'), 'nsclc_stg1': PosixPath('nsclc_stg1.yaml'), 'nsclc_stg23_resectable': PosixPath('nsclc_stg23_resectable.yaml'), 'nsclc_stg3_unresectable': PosixPath('nsclc_stg3_unresectable.yaml'), 'nsclc_stg4_driver': PosixPath('nsclc_stg4_driver.yaml'), 'nsclc_stg4_nodrivers': PosixPath('nsclc_stg4_nodrivers.yaml')}, regimen_registry=PosixPath('nsclc_regimen_registry.yaml'), concept_map=PosixPath('../../mappers/concept_maps.yaml'), measurement_map=PosixPath('../../mappers/measurement_mappers.yaml'), observation_map=PosixPath('../../mappers/observation_mappers.yaml'), entry_graph='nsclc', pathways={'nsclc_stage1': 'nsclc_stg1', 'nsclc_stage23_resectable': 'nsclc_stg23_resectable', 'nsclc_stage3_unresectable': 'nsclc_stg3_unresectable', 'nsclc_stage4_driver': 'nsclc_stg4_driver', 'nsclc_stage4_nodrivers': 'nsclc_stg4_nodrivers'})

In [3]:
def _entry_rows(*, resolver_type: str | None = None, public_only: bool | None = None) -> list[dict]:
    rows = []
    for entry_id, entry in REGISTRY_MODEL.entries.items():
        if resolver_type is not None and entry.resolver.type != resolver_type:
            continue
        if public_only is not None and entry.public != public_only:
            continue
        rows.append(
            {
                "entry_id": entry_id,
                "public": entry.public,
                "clinical_group": entry.clinical_group,
                "stage_scope": ", ".join(entry.stage_scope),
                "resolver_type": entry.resolver.type,
                "required_modifiers": ", ".join(entry.required_modifiers),
            }
        )
    return rows


def list_bundle_entries(public_only: bool | None = None) -> pd.DataFrame:
    return pd.DataFrame(_entry_rows(resolver_type="bundle_recipe", public_only=public_only)).sort_values(
        ["public", "clinical_group", "entry_id"], ascending=[False, True, True]
    )


def list_variant_entries(public_only: bool | None = None) -> pd.DataFrame:
    return pd.DataFrame(_entry_rows(resolver_type="component_query", public_only=public_only)).sort_values(
        ["public", "clinical_group", "entry_id"], ascending=[False, True, True]
    )


list_bundle_entries(public_only=True)

,entry_id,public,clinical_group,stage_scope,resolver_type,required_modifiers
2,port,True,local_stage_i,stage_i,bundle_recipe,"condition_episode.operability, treatment_episo..."
3,port_adjuvant_osimertinib,True,local_stage_i,stage_i,bundle_recipe,"condition_episode.operability, treatment_episo..."
0,sbrt,True,local_stage_i,stage_i,bundle_recipe,condition_episode.operability
4,surgery_adjuvant_osimertinib,True,local_stage_i,stage_i,bundle_recipe,"condition_episode.operability, treatment_episo..."
1,surgery_only,True,local_stage_i,stage_i,bundle_recipe,"condition_episode.operability, treatment_episo..."
7,concurrent_crt,True,unresectable_stage_iii,"stage_iii, unresectable",bundle_recipe,"condition_episode.crt_eligible, condition_epis..."
11,concurrent_crt_adjuvant_durvalumab,True,unresectable_stage_iii,"stage_iii, unresectable",bundle_recipe,"condition_episode.crt_eligible, condition_epis..."
9,concurrent_crt_adjuvant_osimertinib,True,unresectable_stage_iii,"stage_iii, unresectable",bundle_recipe,"condition_episode.crt_eligible, condition_epis..."
5,radiotherapy,True,unresectable_stage_iii,"stage_iii, unresectable",bundle_recipe,condition_episode.crt_eligible
6,sequential_crt,True,unresectable_stage_iii,"stage_iii, unresectable",bundle_recipe,"condition_episode.sequential_crt_eligible, con..."
10,sequential_crt_adjuvant_durvalumab,True,unresectable_stage_iii,"stage_iii, unresectable",bundle_recipe,"condition_episode.sequential_crt_eligible, con..."
8,sequential_crt_adjuvant_osimertinib,True,unresectable_stage_iii,"stage_iii, unresectable",bundle_recipe,"condition_episode.sequential_crt_eligible, con..."

In [4]:
def resolve_entry(entry_id: str) -> dict:
    entry = REGISTRY_MODEL.get_entry(entry_id)
    resolved_query = REGISTRY_MODEL.resolve_hemonc_query(entry_id)
    resolved_bundle = REGISTRY_MODEL.resolve_hemonc_bundle(entry_id)
    payload = {
        "entry_id": entry_id,
        "resolver_type": entry.resolver.type,
        "clinical_group": entry.clinical_group,
        "required_modifiers": entry.required_modifiers,
    }
    if resolved_query is not None:
        payload["resolved_query"] = resolved_query.model_dump()
        payload["normalized_component_requirements"] = apply_default_component_requirements(
            {
                "component_lists": resolved_query.component_lists,
                "category_restrictions": resolved_query.category_restrictions,
                "category_restrictions_provided": resolved_query.category_restrictions_provided,
            }
        )
    if resolved_bundle is not None:
        payload["resolved_bundle"] = resolved_bundle.model_dump()
    return payload


resolve_entry("sequential_crt")

{'entry_id': 'sequential_crt',
 'resolver_type': 'bundle_recipe',
 'clinical_group': 'unresectable_stage_iii',
 'required_modifiers': ['condition_episode.sequential_crt_eligible',
  'condition_occurrence.egfr',
  'condition_occurrence.pdl1_binary'],
 'resolved_bundle': {'group_id': 'sequential_crt',
  'basis': 'sig_bundle',
  'assembly_mode': 'variant_plus_rt',
  'sequence_template': 'sequential',
  'resolved_condition_cuis': [30824,
   30898,
   154361,
   30910,
   52958,
   54044,
   46104,
   13094,
   642,
   25309,
   25316,
   149626,
   157580,
   18383,
   30982],
  'phases': [{'phase_id': 'systemic',
    'title': None,
    'phase_type': 'systemic',
    'timing': 'pre',
    'source_type': 'group',
    'source_entry_id': None,
    'source_group_id': 'nsclc_crt_backbone',
    'component_terms': [],
    'resolved_condition_cuis': [30824,
     30898,
     154361,
     30910,
     52958,
     54044,
     46104,
     13094,
     642,
     25309,
     25316,
     149626,
     157580,
     18383,
     30982],
    'resolved_query': {'group_id': 'nsclc_crt_backbone',
     'basis': 'variant',
     'default_condition_cuis': [30824,
      30898,
      154361,
      30910,
      52958,
      54044,
      46104,
      13094,
      642,
      25309,
      25316,
      149626,
      157580,
      18383,
      30982],
     'component_lists': [['Platinum agent']],
     'category_restrictions': {'chemotherapy': {'type': 'exact', 'amount': 2}},
     'category_restrictions_provided': True},
    'notes': None},
   {'phase_id': 'radiotherapy',
    'title': None,
    'phase_type': 'radiotherapy',
    'timing': 'post',
    'source_type': 'sig_component',
    'source_entry_id': None,
    'source_group_id': None,
    'component_terms': ['External beam radiotherapy'],
    'resolved_condition_cuis': [30824,
     30898,
     154361,
     30910,
     52958,
     54044,
     46104,
     13094,
     642,
     25309,
     25316,
     149626,
     157580,
     18383,
     30982],
    'resolved_query': None,
    'notes': None}],
  'notes': None}}

In [5]:
def compile_entry(entry_id: str) -> dict:
    resolved_query = REGISTRY_MODEL.resolve_hemonc_query(entry_id)
    if resolved_query is not None:
        normalized_requirements = apply_default_component_requirements(
            {
                "component_lists": resolved_query.component_lists,
                "category_restrictions": resolved_query.category_restrictions,
                "category_restrictions_provided": resolved_query.category_restrictions_provided,
            }
        )
        artifacts = build_variant_query_artifacts(resolved_query)
        return {
            "mode": "variant",
            "resolved_query": resolved_query.model_dump(),
            "normalized_component_requirements": normalized_requirements,
            "variant_cui_sql": str(
                artifacts.variant_cuis_subquery.select().compile(
                    compile_kwargs={"literal_binds": True}
                )
            ),
            "variants_sql": str(
                artifacts.variants_stmt.compile(compile_kwargs={"literal_binds": True})
            ),
        }

    bundle_artifacts = build_bundle_query_artifacts_for_entry(REGISTRY_MODEL, entry_id)
    if bundle_artifacts is not None:
        return {
            "mode": "bundle",
            "recipe_id": bundle_artifacts["recipe_id"],
            "assembly_mode": bundle_artifacts["assembly_mode"],
            "sequence_template": bundle_artifacts["sequence_template"],
            "phase_sql": {
                phase_id: str(stmt.compile(compile_kwargs={"literal_binds": True}))
                for phase_id, stmt in bundle_artifacts["phase_statements"].items()
            },
        }

    raise ValueError(f"{entry_id} does not resolve to a variant query or bundle recipe.")


compile_entry("concurrent_crt")

{'mode': 'bundle',
 'recipe_id': 'concurrent_crt',
 'assembly_mode': 'variant_plus_rt',
 'sequence_template': 'concurrent',
 'phase_sql': {'systemic': "SELECT variants.id, variants.allsigshavecyclesigs, variants.allsigshavedose, variants.allsigshavedoseunit, variants.allsigshaveduration, variants.allsigshavedurationunit, variants.allsigshavefrequency, variants.allsigshaveroute, variants.allsigshaveschedule, variants.allsigshavesequence, variants.blob_version, variants.branches, variants.components, variants.cyclesigs, variants.date_added, variants.date_study_modified, variants.date_tracer_modified, variants.fullyspecified, variants.portions, variants.regimen, variants.regimen_cui, variants.routes, variants.sigs, variants.temp, variants.timings, variants.variant, variants.variant_cui, variants.version \nFROM variants JOIN (SELECT anon_2.variant_cui AS variant_cui \nFROM (SELECT DISTINCT anon_3.variant_cui AS variant_cui, anon_3.canmed_major_class AS canmed_major_class, anon_3.canmed_minor_class AS canmed_minor_class, anon_3.main_class AS main_class, anon_3.component AS component, anon_3.component_cui AS component_cui, coalesce(CASE WHEN (anon_3.canmed_major_class = 'Serine-threonine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'MEK inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Immunostimulatory monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Antineoplastic monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Alkylating agent') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Microtubule inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Tyrosine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Topoisomerase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Antimetabolite') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Emesis prevention') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Chemotherapy protective agent') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Growth factor') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Antibody-drug conjugate') THEN 'immunotherapy' END, CASE WHEN (anon_3.main_class = 'TRK inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'KRAS inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-EGFR-HGFR bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Anthracycline') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Multikinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'MET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Steroid') THEN 'supportive' WHEN (anon_3.main_class = 'Antihistamine') THEN 'supportive' WHEN (anon_3.main_class = 'H2 blocker') THEN 'supportive' WHEN (anon_3.main_class = 'Opioid receptor agonist') THEN 'supportive' WHEN (anon_3.main_class = 'Replacement therapy') THEN 'supportive' WHEN (anon_3.main_class = 'Anti-PD-1-VEGF bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Dopamine receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'Fluoroquinolone') THEN 'supportive' WHEN (anon_3.main_class = 'H2-receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'ROS1 inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'RET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-DLL3-CD3 bispecific antibody') THEN 'immunotherapy' END, CASE WHEN (anon_3.component = 'Bleomycin') THEN 'supportive' WHEN (anon_3.component = 'Granulocyte colony-stimulating factor') THEN 'supportive' WHEN (anon_3.component = 'Serotonin 5-HT3 antagonist') THEN 'supportive' WHEN (anon_3.component = 'Steroid') THEN 'supportive' WHEN (anon_3.component = 'External beam radiotherapy') THEN 'radiotherapy' WHEN (anon_3.component = 'Surgery') THEN 'surgery' WHEN (anon_3.component = 'Emesis prevention') THEN 'supportive' END) AS broad_category \nFROM (SELECT variants.variant_cui AS variant_cui, sigs.component AS component, sigs.component_cui AS component_cui, drugs.drug_inn AS drug_inn, drugs.main_class AS main_class, drugs_canmed_major_class.canmed_major_class AS canmed_major_class, drugs_canmed_minor_class.canmed_minor_class AS canmed_minor_class \nFROM variants JOIN sigs ON sigs.variant_cui = variants.variant_cui LEFT OUTER JOIN drugs ON sigs.component_cui = drugs.drug_cui LEFT OUTER JOIN drugs_canmed_major_class ON drugs_canmed_major_class.parent_id = drugs.id LEFT OUTER JOIN drugs_canmed_minor_class ON drugs_canmed_minor_class.parent_id = drugs.id \nWHERE EXISTS (SELECT 1 \nFROM studies, variants_study \nWHERE variants.id = variants_study.parent_id AND studies.study = variants_study.study AND studies.condition_cui IN (30824, 30898, 154361, 30910, 52958, 54044, 46104, 13094, 642, 25309, 25316, 149626, 157580, 18383, 30982))) AS anon_3) AS anon_2 GROUP BY anon_2.variant_cui \nHAVING sum(CASE WHEN (anon_2.broad_category = 'radiotherapy') THEN 1 ELSE 0 END) = 0 AND sum(CASE WHEN (anon_2.broad_category = 'surgery') THEN 1 ELSE 0 END) = 0 AND sum(CASE WHEN (anon_2.broad_category = 'chemotherapy') THEN 1 ELSE 0 END) = 2 AND sum(CASE WHEN (anon_2.broad_category = 'immunotherapy') THEN 1 ELSE 0 END) = 0 AND sum(CASE WHEN (anon_2.component_cui IN (SELECT anon_4.component_cui \nFROM (SELECT DISTINCT anon_2.component_cui AS component_cui \nFROM (SELECT DISTINCT anon_3.variant_cui AS variant_cui, anon_3.canmed_major_class AS canmed_major_class, anon_3.canmed_minor_class AS canmed_minor_class, anon_3.main_class AS main_class, anon_3.component AS component, anon_3.component_cui AS component_cui, coalesce(CASE WHEN (anon_3.canmed_major_class = 'Serine-threonine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'MEK inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Immunostimulatory monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Antineoplastic monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Alkylating agent') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Microtubule inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Tyrosine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Topoisomerase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Antimetabolite') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Emesis prevention') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Chemotherapy protective agent') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Growth factor') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Antibody-drug conjugate') THEN 'immunotherapy' END, CASE WHEN (anon_3.main_class = 'TRK inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'KRAS inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-EGFR-HGFR bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Anthracycline') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Multikinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'MET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Steroid') THEN 'supportive' WHEN (anon_3.main_class = 'Antihistamine') THEN 'supportive' WHEN (anon_3.main_class = 'H2 blocker') THEN 'supportive' WHEN (anon_3.main_class = 'Opioid receptor agonist') THEN 'supportive' WHEN (anon_3.main_class = 'Replacement therapy') THEN 'supportive' WHEN (anon_3.main_class = 'Anti-PD-1-VEGF bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Dopamine receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'Fluoroquinolone') THEN 'supportive' WHEN (anon_3.main_class = 'H2-receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'ROS1 inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'RET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-DLL3-CD3 bispecific antibody') THEN 'immunotherapy' END, CASE WHEN (anon_3.component = 'Bleomycin') THEN 'supportive' WHEN (anon_3.component = 'Granulocyte colony-stimulating factor') THEN 'supportive' WHEN (anon_3.component = 'Serotonin 5-HT3 antagonist') THEN 'supportive' WHEN (anon_3.component = 'Steroid') THEN 'supportive' WHEN (anon_3.component = 'External beam radiotherapy') THEN 'radiotherapy' WHEN (anon_3.component = 'Surgery') THEN 'surgery' WHEN (anon_3.component = 'Emesis prevention') THEN 'supportive' END) AS broad_category \nFROM (SELECT variants.variant_cui AS variant_cui, sigs.component AS component, sigs.component_cui AS component_cui, drugs.drug_inn AS drug_inn, drugs.main_class AS main_class, drugs_canmed_major_class.canmed_major_class AS canmed_major_class, drugs_canmed_minor_class.canmed_minor_class AS canmed_minor_class \nFROM variants JOIN sigs ON sigs.variant_cui = variants.variant_cui LEFT OUTER JOIN drugs ON sigs.component_cui = drugs.drug_cui LEFT OUTER JOIN drugs_canmed_major_class ON drugs_canmed_major_class.parent_id = drugs.id LEFT OUTER JOIN drugs_canmed_minor_class ON drugs_canmed_minor_class.parent_id = drugs.id \nWHERE EXISTS (SELECT 1 \nFROM studies, variants_study \nWHERE variants.id = variants_study.parent_id AND studies.study = variants_study.study AND studies.condition_cui IN (30824, 30898, 154361, 30910, 52958, 54044, 46104, 13094, 642, 25309, 25316, 149626, 157580, 18383, 30982))) AS anon_3) AS anon_2 \nWHERE lower(anon_2.canmed_major_class) LIKE lower('Platinum agent') OR lower(anon_2.canmed_minor_class) LIKE lower('Platinum agent') OR lower(anon_2.main_class) LIKE lower('Platinum agent') OR lower(anon_2.component) LIKE lower('Platinum agent')) AS anon_4)) THEN 1 ELSE 0 END) >= 1) AS anon_1 ON variants.variant_cui = anon_1.variant_cui",
  'radiotherapy': "SELECT sigs.id, sigs.alldays, sigs.branch, sigs.branch_type, sigs.class_field, sigs.component, sigs.component_cui, sigs.component_role, sigs.cycle_length_lb, sigs.cycle_length_ub, sigs.cycle_length_unit, sigs.cyclesigs, sigs.date_added, sigs.divided, sigs.dosecapnum, sigs.dosecapunit, sigs.dosecapunit_cui, sigs.dosemaxnum, sigs.doseminnum, sigs.doseunit, sigs.doseunit_cui, sigs.durationmaxnum, sigs.durationminnum, sigs.durationunit, sigs.durationunit_cui, sigs.frequency, sigs.frequency_cui, sigs.phase, sigs.portion, sigs.regimen, sigs.regimen_cui, sigs.route, sigs.route_cui, sigs.seqrelwhat, sigs.sequence, sigs.step_number, sigs.study, sigs.tail, sigs.targetlevel, sigs.targetleveltype, sigs.targetlevelunit, sigs.targetlevelunit_cui, sigs.temp, sigs.timing_sequence, sigs.variant, sigs.variant_cui \nFROM sigs \nWHERE lower(sigs.component) LIKE lower('External beam radiotherapy')"}}

## Live Execution Helpers

The helpers below require `HEMONC_ENGINE_URL` to be set.

In [6]:
def _require_engine_url(engine_url: str | None = None) -> str:
    resolved = engine_url or HEMONC_ENGINE_URL
    if not resolved:
        raise ValueError("Set HEMONC_ENGINE_URL or pass engine_url explicitly.")
    return resolved


def _variant_row(variant) -> dict:
    return {
        "variant_cui": getattr(variant, "variant_cui", None),
        "variant": getattr(variant, "variant", None),
        "regimen": getattr(variant, "regimen", None),
        "version": getattr(variant, "version", None),
        "has_radiation_sig": getattr(variant, "has_radiation_sig", None),
        "has_non_radiation_sig": getattr(variant, "has_non_radiation_sig", None),
        "is_concurrent_chemort": getattr(variant, "is_concurrent_chemort", None),
        "is_rt_only": getattr(variant, "is_rt_only", None),
        "study_count": len(getattr(variant, "study_objects", []) or []),
        "condition_count": len(getattr(variant, "condition_objects", []) or []),
    }


def _sig_row(sig) -> dict:
    return {
        "sig_id": getattr(sig, "id", None),
        "variant_cui": getattr(sig, "variant_cui", None),
        "component": getattr(sig, "component", None),
        "regimen": getattr(sig, "regimen", None),
        "phase": getattr(sig, "phase", None),
        "sequence": getattr(sig, "sequence", None),
        "timing_sequence": getattr(sig, "timing_sequence", None),
        "study_count": len(getattr(sig, "study_objects", []) or []),
        "condition_count": len(getattr(sig, "condition_objects", []) or []),
    }


def _bundle_row(bundle) -> dict:
    return {
        "recipe_id": bundle.recipe_id,
        "bundle_name": bundle.bundle_name,
        "variant_cui": bundle.variant_cui,
        "assembly_mode": bundle.assembly_mode,
        "sequence_template": bundle.sequence_template,
        "phase_count": len(bundle.phases),
        "phase_summary": " | ".join(
            f"{phase.phase_id}:{phase.phase_type}:{phase.timing}:{phase.label}"
            for phase in bundle.phases
        ),
    }


def run_entry(
    entry_id: str,
    engine_url: str | None = None,
    *,
    limit: int = 20,
    phase_example_limit: int = 10,
) -> dict:
    resolved_query = REGISTRY_MODEL.resolve_hemonc_query(entry_id)
    resolved_bundle = REGISTRY_MODEL.resolve_hemonc_bundle(entry_id)
    if resolved_query is None and resolved_bundle is None:
        raise ValueError(f"{entry_id} does not resolve to a variant query or bundle recipe.")

    engine = sa.create_engine(_require_engine_url(engine_url))
    with so.Session(engine) as session:
        if resolved_query is not None:
            variants = execute_variant_query(session, resolved_query)
            rows = pd.DataFrame([_variant_row(variant) for variant in variants[:limit]])
            return {
                "mode": "variant",
                "row_count": len(variants),
                "rows": rows,
            }

        bundle_artifacts = build_bundle_query_artifacts_for_entry(REGISTRY_MODEL, entry_id)
        phase_records = {
            phase_id: session.execute(stmt).unique().scalars().all()
            for phase_id, stmt in bundle_artifacts["phase_statements"].items()
        }
        bundles = execute_bundle_query_for_entry(session, REGISTRY_MODEL, entry_id)

        phase_counts = pd.DataFrame(
            [
                {"phase_id": phase_id, "row_count": len(records)}
                for phase_id, records in phase_records.items()
            ]
        )
        phase_examples = {
            phase_id: pd.DataFrame(
                [
                    _sig_row(record) if hasattr(record, "component") and not hasattr(record, "variant")
                    else _variant_row(record)
                    for record in records[:phase_example_limit]
                ]
            )
            for phase_id, records in phase_records.items()
        }
        bundle_rows = pd.DataFrame([_bundle_row(bundle) for bundle in bundles[:limit]])
        return {
            "mode": "bundle",
            "phase_counts": phase_counts,
            "phase_examples": phase_examples,
            "bundle_count": len(bundles),
            "bundle_rows": bundle_rows,
        }


def display_entry_run(entry_id: str, engine_url: str | None = None, *, limit: int = 20, phase_example_limit: int = 10):
    result = run_entry(entry_id, engine_url=engine_url, limit=limit, phase_example_limit=phase_example_limit)
    display(Markdown(f"## `{entry_id}` ({result['mode']})"))
    if result["mode"] == "variant":
        display(Markdown(f"Matched variants: **{result['row_count']}**"))
        display(result["rows"])
        return result

    display(Markdown(f"Assembled bundles: **{result['bundle_count']}**"))
    display(Markdown("### Phase counts"))
    display(result["phase_counts"])
    display(Markdown("### Bundle rows"))
    display(result["bundle_rows"])
    for phase_id, frame in result["phase_examples"].items():
        display(Markdown(f"### Phase examples: `{phase_id}`"))
        display(frame)
    return result


if HEMONC_ENGINE_URL:
    display(Markdown("`HEMONC_ENGINE_URL` detected. Live execution is available."))
else:
    display(Markdown("Set `HEMONC_ENGINE_URL` to enable live execution cells."))

`HEMONC_ENGINE_URL` detected. Live execution is available.

In [7]:
# Example: compare how stage III bundle recipes are defined before executing them.
bundle_examples = [
    "radiotherapy",
    "sequential_crt",
    "concurrent_crt",
    "sequential_crt_adjuvant_durvalumab",
    "concurrent_crt_adjuvant_durvalumab",
]

pd.DataFrame([resolve_entry(entry_id) for entry_id in bundle_examples])

,entry_id,resolver_type,clinical_group,required_modifiers,resolved_bundle
0,radiotherapy,bundle_recipe,unresectable_stage_iii,[condition_episode.crt_eligible],"{'group_id': 'radiotherapy', 'basis': 'sig_bun..."
1,sequential_crt,bundle_recipe,unresectable_stage_iii,"[condition_episode.sequential_crt_eligible, co...","{'group_id': 'sequential_crt', 'basis': 'sig_b..."
2,concurrent_crt,bundle_recipe,unresectable_stage_iii,"[condition_episode.crt_eligible, condition_epi...","{'group_id': 'concurrent_crt', 'basis': 'sig_b..."
3,sequential_crt_adjuvant_durvalumab,bundle_recipe,unresectable_stage_iii,"[condition_episode.sequential_crt_eligible, co...",{'group_id': 'sequential_crt_adjuvant_durvalum...
4,concurrent_crt_adjuvant_durvalumab,bundle_recipe,unresectable_stage_iii,"[condition_episode.crt_eligible, condition_epi...",{'group_id': 'concurrent_crt_adjuvant_durvalum...

In [8]:
# Example: inspect compiled SQL for one bundle recipe.
compile_entry("sequential_crt")

{'mode': 'bundle',
 'recipe_id': 'sequential_crt',
 'assembly_mode': 'variant_plus_rt',
 'sequence_template': 'sequential',
 'phase_sql': {'systemic': "SELECT variants.id, variants.allsigshavecyclesigs, variants.allsigshavedose, variants.allsigshavedoseunit, variants.allsigshaveduration, variants.allsigshavedurationunit, variants.allsigshavefrequency, variants.allsigshaveroute, variants.allsigshaveschedule, variants.allsigshavesequence, variants.blob_version, variants.branches, variants.components, variants.cyclesigs, variants.date_added, variants.date_study_modified, variants.date_tracer_modified, variants.fullyspecified, variants.portions, variants.regimen, variants.regimen_cui, variants.routes, variants.sigs, variants.temp, variants.timings, variants.variant, variants.variant_cui, variants.version \nFROM variants JOIN (SELECT anon_2.variant_cui AS variant_cui \nFROM (SELECT DISTINCT anon_3.variant_cui AS variant_cui, anon_3.canmed_major_class AS canmed_major_class, anon_3.canmed_minor_class AS canmed_minor_class, anon_3.main_class AS main_class, anon_3.component AS component, anon_3.component_cui AS component_cui, coalesce(CASE WHEN (anon_3.canmed_major_class = 'Serine-threonine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'MEK inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Immunostimulatory monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Antineoplastic monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Alkylating agent') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Microtubule inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Tyrosine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Topoisomerase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Antimetabolite') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Emesis prevention') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Chemotherapy protective agent') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Growth factor') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Antibody-drug conjugate') THEN 'immunotherapy' END, CASE WHEN (anon_3.main_class = 'TRK inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'KRAS inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-EGFR-HGFR bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Anthracycline') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Multikinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'MET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Steroid') THEN 'supportive' WHEN (anon_3.main_class = 'Antihistamine') THEN 'supportive' WHEN (anon_3.main_class = 'H2 blocker') THEN 'supportive' WHEN (anon_3.main_class = 'Opioid receptor agonist') THEN 'supportive' WHEN (anon_3.main_class = 'Replacement therapy') THEN 'supportive' WHEN (anon_3.main_class = 'Anti-PD-1-VEGF bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Dopamine receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'Fluoroquinolone') THEN 'supportive' WHEN (anon_3.main_class = 'H2-receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'ROS1 inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'RET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-DLL3-CD3 bispecific antibody') THEN 'immunotherapy' END, CASE WHEN (anon_3.component = 'Bleomycin') THEN 'supportive' WHEN (anon_3.component = 'Granulocyte colony-stimulating factor') THEN 'supportive' WHEN (anon_3.component = 'Serotonin 5-HT3 antagonist') THEN 'supportive' WHEN (anon_3.component = 'Steroid') THEN 'supportive' WHEN (anon_3.component = 'External beam radiotherapy') THEN 'radiotherapy' WHEN (anon_3.component = 'Surgery') THEN 'surgery' WHEN (anon_3.component = 'Emesis prevention') THEN 'supportive' END) AS broad_category \nFROM (SELECT variants.variant_cui AS variant_cui, sigs.component AS component, sigs.component_cui AS component_cui, drugs.drug_inn AS drug_inn, drugs.main_class AS main_class, drugs_canmed_major_class.canmed_major_class AS canmed_major_class, drugs_canmed_minor_class.canmed_minor_class AS canmed_minor_class \nFROM variants JOIN sigs ON sigs.variant_cui = variants.variant_cui LEFT OUTER JOIN drugs ON sigs.component_cui = drugs.drug_cui LEFT OUTER JOIN drugs_canmed_major_class ON drugs_canmed_major_class.parent_id = drugs.id LEFT OUTER JOIN drugs_canmed_minor_class ON drugs_canmed_minor_class.parent_id = drugs.id \nWHERE EXISTS (SELECT 1 \nFROM studies, variants_study \nWHERE variants.id = variants_study.parent_id AND studies.study = variants_study.study AND studies.condition_cui IN (30824, 30898, 154361, 30910, 52958, 54044, 46104, 13094, 642, 25309, 25316, 149626, 157580, 18383, 30982))) AS anon_3) AS anon_2 GROUP BY anon_2.variant_cui \nHAVING sum(CASE WHEN (anon_2.broad_category = 'radiotherapy') THEN 1 ELSE 0 END) = 0 AND sum(CASE WHEN (anon_2.broad_category = 'surgery') THEN 1 ELSE 0 END) = 0 AND sum(CASE WHEN (anon_2.broad_category = 'chemotherapy') THEN 1 ELSE 0 END) = 2 AND sum(CASE WHEN (anon_2.broad_category = 'immunotherapy') THEN 1 ELSE 0 END) = 0 AND sum(CASE WHEN (anon_2.component_cui IN (SELECT anon_4.component_cui \nFROM (SELECT DISTINCT anon_2.component_cui AS component_cui \nFROM (SELECT DISTINCT anon_3.variant_cui AS variant_cui, anon_3.canmed_major_class AS canmed_major_class, anon_3.canmed_minor_class AS canmed_minor_class, anon_3.main_class AS main_class, anon_3.component AS component, anon_3.component_cui AS component_cui, coalesce(CASE WHEN (anon_3.canmed_major_class = 'Serine-threonine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'MEK inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Immunostimulatory monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Antineoplastic monoclonal antibody') THEN 'immunotherapy' WHEN (anon_3.canmed_major_class = 'Alkylating agent') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Microtubule inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Tyrosine kinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Topoisomerase inhibitor') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Antimetabolite') THEN 'chemotherapy' WHEN (anon_3.canmed_major_class = 'Emesis prevention') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Chemotherapy protective agent') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Growth factor') THEN 'supportive' WHEN (anon_3.canmed_major_class = 'Antibody-drug conjugate') THEN 'immunotherapy' END, CASE WHEN (anon_3.main_class = 'TRK inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'KRAS inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-EGFR-HGFR bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Anthracycline') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Multikinase inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'MET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Steroid') THEN 'supportive' WHEN (anon_3.main_class = 'Antihistamine') THEN 'supportive' WHEN (anon_3.main_class = 'H2 blocker') THEN 'supportive' WHEN (anon_3.main_class = 'Opioid receptor agonist') THEN 'supportive' WHEN (anon_3.main_class = 'Replacement therapy') THEN 'supportive' WHEN (anon_3.main_class = 'Anti-PD-1-VEGF bispecific antibody') THEN 'immunotherapy' WHEN (anon_3.main_class = 'Dopamine receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'Fluoroquinolone') THEN 'supportive' WHEN (anon_3.main_class = 'H2-receptor antagonist') THEN 'supportive' WHEN (anon_3.main_class = 'ROS1 inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'RET inhibitor') THEN 'chemotherapy' WHEN (anon_3.main_class = 'Anti-DLL3-CD3 bispecific antibody') THEN 'immunotherapy' END, CASE WHEN (anon_3.component = 'Bleomycin') THEN 'supportive' WHEN (anon_3.component = 'Granulocyte colony-stimulating factor') THEN 'supportive' WHEN (anon_3.component = 'Serotonin 5-HT3 antagonist') THEN 'supportive' WHEN (anon_3.component = 'Steroid') THEN 'supportive' WHEN (anon_3.component = 'External beam radiotherapy') THEN 'radiotherapy' WHEN (anon_3.component = 'Surgery') THEN 'surgery' WHEN (anon_3.component = 'Emesis prevention') THEN 'supportive' END) AS broad_category \nFROM (SELECT variants.variant_cui AS variant_cui, sigs.component AS component, sigs.component_cui AS component_cui, drugs.drug_inn AS drug_inn, drugs.main_class AS main_class, drugs_canmed_major_class.canmed_major_class AS canmed_major_class, drugs_canmed_minor_class.canmed_minor_class AS canmed_minor_class \nFROM variants JOIN sigs ON sigs.variant_cui = variants.variant_cui LEFT OUTER JOIN drugs ON sigs.component_cui = drugs.drug_cui LEFT OUTER JOIN drugs_canmed_major_class ON drugs_canmed_major_class.parent_id = drugs.id LEFT OUTER JOIN drugs_canmed_minor_class ON drugs_canmed_minor_class.parent_id = drugs.id \nWHERE EXISTS (SELECT 1 \nFROM studies, variants_study \nWHERE variants.id = variants_study.parent_id AND studies.study = variants_study.study AND studies.condition_cui IN (30824, 30898, 154361, 30910, 52958, 54044, 46104, 13094, 642, 25309, 25316, 149626, 157580, 18383, 30982))) AS anon_3) AS anon_2 \nWHERE lower(anon_2.canmed_major_class) LIKE lower('Platinum agent') OR lower(anon_2.canmed_minor_class) LIKE lower('Platinum agent') OR lower(anon_2.main_class) LIKE lower('Platinum agent') OR lower(anon_2.component) LIKE lower('Platinum agent')) AS anon_4)) THEN 1 ELSE 0 END) >= 1) AS anon_1 ON variants.variant_cui = anon_1.variant_cui",
  'radiotherapy': "SELECT sigs.id, sigs.alldays, sigs.branch, sigs.branch_type, sigs.class_field, sigs.component, sigs.component_cui, sigs.component_role, sigs.cycle_length_lb, sigs.cycle_length_ub, sigs.cycle_length_unit, sigs.cyclesigs, sigs.date_added, sigs.divided, sigs.dosecapnum, sigs.dosecapunit, sigs.dosecapunit_cui, sigs.dosemaxnum, sigs.doseminnum, sigs.doseunit, sigs.doseunit_cui, sigs.durationmaxnum, sigs.durationminnum, sigs.durationunit, sigs.durationunit_cui, sigs.frequency, sigs.frequency_cui, sigs.phase, sigs.portion, sigs.regimen, sigs.regimen_cui, sigs.route, sigs.route_cui, sigs.seqrelwhat, sigs.sequence, sigs.step_number, sigs.study, sigs.tail, sigs.targetlevel, sigs.targetleveltype, sigs.targetlevelunit, sigs.targetlevelunit_cui, sigs.temp, sigs.timing_sequence, sigs.variant, sigs.variant_cui \nFROM sigs \nWHERE lower(sigs.component) LIKE lower('External beam radiotherapy')"}}

In [9]:
display_entry_run("radiotherapy")

## `radiotherapy` (bundle)

Assembled bundles: **38**

### Phase counts

       phase_id  row_count
0  radiotherapy        506

### Bundle rows

,recipe_id,bundle_name,variant_cui,assembly_mode,sequence_template,phase_count,phase_summary
0,radiotherapy,External beam radiotherapy,136654,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
1,radiotherapy,External beam radiotherapy,136655,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
2,radiotherapy,External beam radiotherapy,136656,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
3,radiotherapy,External beam radiotherapy,136657,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
4,radiotherapy,External beam radiotherapy,130427,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
5,radiotherapy,External beam radiotherapy,130428,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
6,radiotherapy,External beam radiotherapy,130429,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
7,radiotherapy,External beam radiotherapy,130429,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
8,radiotherapy,External beam radiotherapy,130430,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
9,radiotherapy,External beam radiotherapy,130460,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
10,radiotherapy,External beam radiotherapy,130512,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
11,radiotherapy,External beam radiotherapy,131025,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
12,radiotherapy,External beam radiotherapy,131026,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
13,radiotherapy,External beam radiotherapy,131032,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
14,radiotherapy,External beam radiotherapy,131033,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
15,radiotherapy,External beam radiotherapy,131034,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
16,radiotherapy,External beam radiotherapy,131045,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
17,radiotherapy,External beam radiotherapy,134538,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
18,radiotherapy,External beam radiotherapy,144851,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...
19,radiotherapy,External beam radiotherapy,130977,rt_only,standalone,1,radiotherapy:radiotherapy:standalone:External ...

### Phase examples: `radiotherapy`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,144918.0,Variant #01,ADT and RT,None,None,None,None,None,13,1
1,144919.0,Variant #02,ADT and RT,None,None,None,None,None,1,1
2,129928.0,Variant #01,Bevacizumab and RT,None,None,None,None,None,1,1
3,129951.0,Variant #01,Bicalutamide and RT,None,None,None,None,None,1,1
4,136628.0,Variant #01,"Bleomycin, Methotrexate, Vinblastine/RT",None,None,None,None,None,1,1
5,136631.0,Variant #01,"BuCyTBI, then allo HSCT",None,None,None,None,None,2,1
6,130207.0,Variant #01,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
7,130208.0,Variant #02,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
8,130209.0,Variant #03,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
9,150915.0,Variant #04,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1

{'mode': 'bundle',
 'phase_counts':        phase_id  row_count
 0  radiotherapy        506,
 'phase_examples': {'radiotherapy':    variant_cui      variant                                  regimen version  \
  0     144918.0  Variant #01                               ADT and RT    None
  1     144919.0  Variant #02                               ADT and RT    None
  2     129928.0  Variant #01                       Bevacizumab and RT    None
  3     129951.0  Variant #01                      Bicalutamide and RT    None
  4     136628.0  Variant #01  Bleomycin, Methotrexate, Vinblastine/RT    None
  5     136631.0  Variant #01                  BuCyTBI, then allo HSCT    None
  6     130207.0  Variant #01   Capecitabine and Cisplatin (CX) and RT    None
  7     130208.0  Variant #02   Capecitabine and Cisplatin (CX) and RT    None
  8     130209.0  Variant #03   Capecitabine and Cisplatin (CX) and RT    None
  9     150915.0  Variant #04   Capecitabine and Cisplatin (CX) and RT    None

    has_radiation_sig has_non_radiation_sig is_concurrent_chemort is_rt_only  \
  0              None                  None                  None       None
  1              None                  None                  None       None
  2              None                  None                  None       None
  3              None                  None                  None       None
  4              None                  None                  None       None
  5              None                  None                  None       None
  6              None                  None                  None       None
  7              None                  None                  None       None
  8              None                  None                  None       None
  9              None                  None                  None       None

     study_count  condition_count
  0           13                1
  1            1                1
  2            1                1
  3            1                1
  4            1                1
  5            2                1
  6            1                1
  7            1                1
  8            1                1
  9            1                1  },
 'bundle_count': 38,
 'bundle_rows':        recipe_id                 bundle_name  variant_cui assembly_mode  \
 0   radiotherapy  External beam radiotherapy       136654       rt_only
 1   radiotherapy  External beam radiotherapy       136655       rt_only
 2   radiotherapy  External beam radiotherapy       136656       rt_only
 3   radiotherapy  External beam radiotherapy       136657       rt_only
 4   radiotherapy  External beam radiotherapy       130427       rt_only
 5   radiotherapy  External beam radiotherapy       130428       rt_only
 6   radiotherapy  External beam radiotherapy       130429       rt_only
 7   radiotherapy  External beam radiotherapy       130429       rt_only
 8   radiotherapy  External beam radiotherapy       130430       rt_only
 9   radiotherapy  External beam radiotherapy       130460       rt_only
 10  radiotherapy  External beam radiotherapy       130512       rt_only
 11  radiotherapy  External beam radiotherapy       131025       rt_only
 12  radiotherapy  External beam radiotherapy       131026       rt_only
 13  radiotherapy  External beam radiotherapy       131032       rt_only
 14  radiotherapy  External beam radiotherapy       131033       rt_only
 15  radiotherapy  External beam radiotherapy       131034       rt_only
 16  radiotherapy  External beam radiotherapy       131045       rt_only
 17  radiotherapy  External beam radiotherapy       134538       rt_only
 18  radiotherapy  External beam radiotherapy       144851       rt_only
 19  radiotherapy  External beam radiotherapy       130977       rt_only

    sequence_template  phase_count  \
 0         standalone            1
 1         standalone            1
 2         standalone            1
 3         standalone            1
 4         standalone            1
 5         standalone            1
 6         standalone            1
 7         standalone            1
 8         standalone            1
 9         standalone            1
 10        standalone            1
 11        standalone            1
 12        standalone            1
 13        standalone            1
 14        standalone            1
 15        standalone            1
 16        standalone            1
 17        standalone            1
 18        standalone            1
 19        standalone            1

                                         phase_summary
 0   radiotherapy:radiotherapy:standalone:External ...
 1   radiotherapy:radiotherapy:standalone:External ...
 2   radiotherapy:radiotherapy:standalone:External ...
 3   radiotherapy:radiotherapy:standalone:External ...
 4   radiotherapy:radiotherapy:standalone:External ...
 5   radiotherapy:radiotherapy:standalone:External ...
 6   radiotherapy:radiotherapy:standalone:External ...
 7   radiotherapy:radiotherapy:standalone:External ...
 8   radiotherapy:radiotherapy:standalone:External ...
 9   radiotherapy:radiotherapy:standalone:External ...
 10  radiotherapy:radiotherapy:standalone:External ...
 11  radiotherapy:radiotherapy:standalone:External ...
 12  radiotherapy:radiotherapy:standalone:External ...
 13  radiotherapy:radiotherapy:standalone:External ...
 14  radiotherapy:radiotherapy:standalone:External ...
 15  radiotherapy:radiotherapy:standalone:External ...
 16  radiotherapy:radiotherapy:standalone:External ...
 17  radiotherapy:radiotherapy:standalone:External ...
 18  radiotherapy:radiotherapy:standalone:External ...
 19  radiotherapy:radiotherapy:standalone:External ...  }

In [10]:
display_entry_run("sequential_crt")

## `sequential_crt` (bundle)

Assembled bundles: **1205**

### Phase counts

       phase_id  row_count
0      systemic        625
1  radiotherapy        506

### Bundle rows

,recipe_id,bundle_name,variant_cui,assembly_mode,sequence_template,phase_count,phase_summary
0,sequential_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Cisplati...
1,sequential_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Cisplati...
2,sequential_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Cisplati...
3,sequential_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Cisplati...
4,sequential_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Cisplati...
5,sequential_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Cisplati...
6,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
7,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
8,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
9,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
10,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
11,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
12,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
13,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
14,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
15,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
16,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
17,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
18,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130269,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...
19,sequential_crt,Carboplatin and Docetaxel (DCb) + External bea...,130269,variant_plus_rt,sequential,2,systemic:systemic:pre:Carboplatin and Docetaxe...

### Phase examples: `systemic`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,130256,Variant #01,Carboplatin and Cisplatin,-3,False,True,False,False,1,1
1,130256,Variant #01,Carboplatin and Cisplatin,-2,False,True,False,False,1,1
2,130256,Variant #01,Carboplatin and Cisplatin,-1,False,True,False,False,1,1
3,130256,Variant #01,Carboplatin and Cisplatin,0,False,True,False,False,1,1
4,130256,Variant #01,Carboplatin and Cisplatin,1,False,True,False,False,1,1
5,130258,Variant #01,Carboplatin and Docetaxel (DCb),0,False,True,False,False,4,3
6,130258,Variant #01,Carboplatin and Docetaxel (DCb),1,False,True,False,False,4,3
7,130262,Variant #05,Carboplatin and Docetaxel (DCb),0,False,True,False,False,2,2
8,130262,Variant #05,Carboplatin and Docetaxel (DCb),1,False,True,False,False,2,2
9,130269,Variant #12,Carboplatin and Docetaxel (DCb),-1,False,True,False,False,4,1

### Phase examples: `radiotherapy`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,144918.0,Variant #01,ADT and RT,None,None,None,None,None,13,1
1,144919.0,Variant #02,ADT and RT,None,None,None,None,None,1,1
2,129928.0,Variant #01,Bevacizumab and RT,None,None,None,None,None,1,1
3,129951.0,Variant #01,Bicalutamide and RT,None,None,None,None,None,1,1
4,136628.0,Variant #01,"Bleomycin, Methotrexate, Vinblastine/RT",None,None,None,None,None,1,1
5,136631.0,Variant #01,"BuCyTBI, then allo HSCT",None,None,None,None,None,2,1
6,130207.0,Variant #01,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
7,130208.0,Variant #02,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
8,130209.0,Variant #03,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
9,150915.0,Variant #04,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1

{'mode': 'bundle',
 'phase_counts':        phase_id  row_count
 0      systemic        625
 1  radiotherapy        506,
 'phase_examples': {'systemic':    variant_cui      variant                          regimen  version  \
  0       130256  Variant #01        Carboplatin and Cisplatin       -3
  1       130256  Variant #01        Carboplatin and Cisplatin       -2
  2       130256  Variant #01        Carboplatin and Cisplatin       -1
  3       130256  Variant #01        Carboplatin and Cisplatin        0
  4       130256  Variant #01        Carboplatin and Cisplatin        1
  5       130258  Variant #01  Carboplatin and Docetaxel (DCb)        0
  6       130258  Variant #01  Carboplatin and Docetaxel (DCb)        1
  7       130262  Variant #05  Carboplatin and Docetaxel (DCb)        0
  8       130262  Variant #05  Carboplatin and Docetaxel (DCb)        1
  9       130269  Variant #12  Carboplatin and Docetaxel (DCb)       -1

     has_radiation_sig  has_non_radiation_sig  is_concurrent_chemort  \
  0              False                   True                  False
  1              False                   True                  False
  2              False                   True                  False
  3              False                   True                  False
  4              False                   True                  False
  5              False                   True                  False
  6              False                   True                  False
  7              False                   True                  False
  8              False                   True                  False
  9              False                   True                  False

     is_rt_only  study_count  condition_count
  0       False            1                1
  1       False            1                1
  2       False            1                1
  3       False            1                1
  4       False            1                1
  5       False            4                3
  6       False            4                3
  7       False            2                2
  8       False            2                2
  9       False            4                1  ,
  'radiotherapy':    variant_cui      variant                                  regimen version  \
  0     144918.0  Variant #01                               ADT and RT    None
  1     144919.0  Variant #02                               ADT and RT    None
  2     129928.0  Variant #01                       Bevacizumab and RT    None
  3     129951.0  Variant #01                      Bicalutamide and RT    None
  4     136628.0  Variant #01  Bleomycin, Methotrexate, Vinblastine/RT    None
  5     136631.0  Variant #01                  BuCyTBI, then allo HSCT    None
  6     130207.0  Variant #01   Capecitabine and Cisplatin (CX) and RT    None
  7     130208.0  Variant #02   Capecitabine and Cisplatin (CX) and RT    None
  8     130209.0  Variant #03   Capecitabine and Cisplatin (CX) and RT    None
  9     150915.0  Variant #04   Capecitabine and Cisplatin (CX) and RT    None

    has_radiation_sig has_non_radiation_sig is_concurrent_chemort is_rt_only  \
  0              None                  None                  None       None
  1              None                  None                  None       None
  2              None                  None                  None       None
  3              None                  None                  None       None
  4              None                  None                  None       None
  5              None                  None                  None       None
  6              None                  None                  None       None
  7              None                  None                  None       None
  8              None                  None                  None       None
  9              None                  None                  None       None

     study_count  condition_count
  0           13                1
  1            1                1
  2            1                1
  3            1                1
  4            1                1
  5            2                1
  6            1                1
  7            1                1
  8            1                1
  9            1                1  },
 'bundle_count': 1205,
 'bundle_rows':          recipe_id                                        bundle_name  \
 0   sequential_crt  Carboplatin and Cisplatin + External beam radi...
 1   sequential_crt  Carboplatin and Cisplatin + External beam radi...
 2   sequential_crt  Carboplatin and Cisplatin + External beam radi...
 3   sequential_crt  Carboplatin and Cisplatin + External beam radi...
 4   sequential_crt  Carboplatin and Cisplatin + External beam radi...
 5   sequential_crt  Carboplatin and Cisplatin + External beam radi...
 6   sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 7   sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 8   sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 9   sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 10  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 11  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 12  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 13  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 14  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 15  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 16  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 17  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 18  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...
 19  sequential_crt  Carboplatin and Docetaxel (DCb) + External bea...

     variant_cui    assembly_mode sequence_template  phase_count  \
 0        130256  variant_plus_rt        sequential            2
 1        130256  variant_plus_rt        sequential            2
 2        130256  variant_plus_rt        sequential            2
 3        130256  variant_plus_rt        sequential            2
 4        130256  variant_plus_rt        sequential            2
 5        130256  variant_plus_rt        sequential            2
 6        130258  variant_plus_rt        sequential            2
 7        130258  variant_plus_rt        sequential            2
 8        130258  variant_plus_rt        sequential            2
 9        130258  variant_plus_rt        sequential            2
 10       130258  variant_plus_rt        sequential            2
 11       130258  variant_plus_rt        sequential            2
 12       130262  variant_plus_rt        sequential            2
 13       130262  variant_plus_rt        sequential            2
 14       130262  variant_plus_rt        sequential            2
 15       130262  variant_plus_rt        sequential            2
 16       130262  variant_plus_rt        sequential            2
 17       130262  variant_plus_rt        sequential            2
 18       130269  variant_plus_rt        sequential            2
 19       130269  variant_plus_rt        sequential            2

                                         phase_summary
 0   systemic:systemic:pre:Carboplatin and Cisplati...
 1   systemic:systemic:pre:Carboplatin and Cisplati...
 2   systemic:systemic:pre:Carboplatin and Cisplati...
 3   systemic:systemic:pre:Carboplatin and Cisplati...
 4   systemic:systemic:pre:Carboplatin and Cisplati...
 5   systemic:systemic:pre:Carboplatin and Cisplati...
 6   systemic:systemic:pre:Carboplatin and Docetaxe...
 7   systemic:systemic:pre:Carboplatin and Docetaxe...
 8   systemic:systemic:pre:Carboplatin and Docetaxe...
 9   systemic:systemic:pre:Carboplatin and Docetaxe...
 10  systemic:systemic:pre:Carboplatin and Docetaxe...
 11  systemic:systemic:pre:Carboplatin and Docetaxe...
 12  systemic:systemic:pre:Carboplatin and Docetaxe...
 13  systemic:systemic:pre:Carboplatin and Docetaxe...
 14  systemic:systemic:pre:Carboplatin and Docetaxe...
 15  systemic:systemic:pre:Carboplatin and Docetaxe...
 16  systemic:systemic:pre:Carboplatin and Docetaxe...
 17  systemic:systemic:pre:Carboplatin and Docetaxe...
 18  systemic:systemic:pre:Carboplatin and Docetaxe...
 19  systemic:systemic:pre:Carboplatin and Docetaxe...  }

In [11]:
display_entry_run("concurrent_crt")

## `concurrent_crt` (bundle)

Assembled bundles: **1205**

### Phase counts

       phase_id  row_count
0      systemic        625
1  radiotherapy        506

### Bundle rows

,recipe_id,bundle_name,variant_cui,assembly_mode,sequence_template,phase_count,phase_summary
0,concurrent_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and C...
1,concurrent_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and C...
2,concurrent_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and C...
3,concurrent_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and C...
4,concurrent_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and C...
5,concurrent_crt,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and C...
6,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
7,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
8,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
9,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
10,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
11,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
12,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
13,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
14,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
15,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
16,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
17,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130262,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
18,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130269,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...
19,concurrent_crt,Carboplatin and Docetaxel (DCb) + External bea...,130269,variant_plus_rt,concurrent,2,systemic:systemic:concurrent:Carboplatin and D...

### Phase examples: `systemic`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,130256,Variant #01,Carboplatin and Cisplatin,-3,False,True,False,False,1,1
1,130256,Variant #01,Carboplatin and Cisplatin,-2,False,True,False,False,1,1
2,130256,Variant #01,Carboplatin and Cisplatin,-1,False,True,False,False,1,1
3,130256,Variant #01,Carboplatin and Cisplatin,0,False,True,False,False,1,1
4,130256,Variant #01,Carboplatin and Cisplatin,1,False,True,False,False,1,1
5,130258,Variant #01,Carboplatin and Docetaxel (DCb),0,False,True,False,False,4,3
6,130258,Variant #01,Carboplatin and Docetaxel (DCb),1,False,True,False,False,4,3
7,130262,Variant #05,Carboplatin and Docetaxel (DCb),0,False,True,False,False,2,2
8,130262,Variant #05,Carboplatin and Docetaxel (DCb),1,False,True,False,False,2,2
9,130269,Variant #12,Carboplatin and Docetaxel (DCb),-1,False,True,False,False,4,1

### Phase examples: `radiotherapy`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,144918.0,Variant #01,ADT and RT,None,None,None,None,None,13,1
1,144919.0,Variant #02,ADT and RT,None,None,None,None,None,1,1
2,129928.0,Variant #01,Bevacizumab and RT,None,None,None,None,None,1,1
3,129951.0,Variant #01,Bicalutamide and RT,None,None,None,None,None,1,1
4,136628.0,Variant #01,"Bleomycin, Methotrexate, Vinblastine/RT",None,None,None,None,None,1,1
5,136631.0,Variant #01,"BuCyTBI, then allo HSCT",None,None,None,None,None,2,1
6,130207.0,Variant #01,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
7,130208.0,Variant #02,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
8,130209.0,Variant #03,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
9,150915.0,Variant #04,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1

{'mode': 'bundle',
 'phase_counts':        phase_id  row_count
 0      systemic        625
 1  radiotherapy        506,
 'phase_examples': {'systemic':    variant_cui      variant                          regimen  version  \
  0       130256  Variant #01        Carboplatin and Cisplatin       -3
  1       130256  Variant #01        Carboplatin and Cisplatin       -2
  2       130256  Variant #01        Carboplatin and Cisplatin       -1
  3       130256  Variant #01        Carboplatin and Cisplatin        0
  4       130256  Variant #01        Carboplatin and Cisplatin        1
  5       130258  Variant #01  Carboplatin and Docetaxel (DCb)        0
  6       130258  Variant #01  Carboplatin and Docetaxel (DCb)        1
  7       130262  Variant #05  Carboplatin and Docetaxel (DCb)        0
  8       130262  Variant #05  Carboplatin and Docetaxel (DCb)        1
  9       130269  Variant #12  Carboplatin and Docetaxel (DCb)       -1

     has_radiation_sig  has_non_radiation_sig  is_concurrent_chemort  \
  0              False                   True                  False
  1              False                   True                  False
  2              False                   True                  False
  3              False                   True                  False
  4              False                   True                  False
  5              False                   True                  False
  6              False                   True                  False
  7              False                   True                  False
  8              False                   True                  False
  9              False                   True                  False

     is_rt_only  study_count  condition_count
  0       False            1                1
  1       False            1                1
  2       False            1                1
  3       False            1                1
  4       False            1                1
  5       False            4                3
  6       False            4                3
  7       False            2                2
  8       False            2                2
  9       False            4                1  ,
  'radiotherapy':    variant_cui      variant                                  regimen version  \
  0     144918.0  Variant #01                               ADT and RT    None
  1     144919.0  Variant #02                               ADT and RT    None
  2     129928.0  Variant #01                       Bevacizumab and RT    None
  3     129951.0  Variant #01                      Bicalutamide and RT    None
  4     136628.0  Variant #01  Bleomycin, Methotrexate, Vinblastine/RT    None
  5     136631.0  Variant #01                  BuCyTBI, then allo HSCT    None
  6     130207.0  Variant #01   Capecitabine and Cisplatin (CX) and RT    None
  7     130208.0  Variant #02   Capecitabine and Cisplatin (CX) and RT    None
  8     130209.0  Variant #03   Capecitabine and Cisplatin (CX) and RT    None
  9     150915.0  Variant #04   Capecitabine and Cisplatin (CX) and RT    None

    has_radiation_sig has_non_radiation_sig is_concurrent_chemort is_rt_only  \
  0              None                  None                  None       None
  1              None                  None                  None       None
  2              None                  None                  None       None
  3              None                  None                  None       None
  4              None                  None                  None       None
  5              None                  None                  None       None
  6              None                  None                  None       None
  7              None                  None                  None       None
  8              None                  None                  None       None
  9              None                  None                  None       None

     study_count  condition_count
  0           13                1
  1            1                1
  2            1                1
  3            1                1
  4            1                1
  5            2                1
  6            1                1
  7            1                1
  8            1                1
  9            1                1  },
 'bundle_count': 1205,
 'bundle_rows':          recipe_id                                        bundle_name  \
 0   concurrent_crt  Carboplatin and Cisplatin + External beam radi...
 1   concurrent_crt  Carboplatin and Cisplatin + External beam radi...
 2   concurrent_crt  Carboplatin and Cisplatin + External beam radi...
 3   concurrent_crt  Carboplatin and Cisplatin + External beam radi...
 4   concurrent_crt  Carboplatin and Cisplatin + External beam radi...
 5   concurrent_crt  Carboplatin and Cisplatin + External beam radi...
 6   concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 7   concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 8   concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 9   concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 10  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 11  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 12  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 13  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 14  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 15  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 16  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 17  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 18  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...
 19  concurrent_crt  Carboplatin and Docetaxel (DCb) + External bea...

     variant_cui    assembly_mode sequence_template  phase_count  \
 0        130256  variant_plus_rt        concurrent            2
 1        130256  variant_plus_rt        concurrent            2
 2        130256  variant_plus_rt        concurrent            2
 3        130256  variant_plus_rt        concurrent            2
 4        130256  variant_plus_rt        concurrent            2
 5        130256  variant_plus_rt        concurrent            2
 6        130258  variant_plus_rt        concurrent            2
 7        130258  variant_plus_rt        concurrent            2
 8        130258  variant_plus_rt        concurrent            2
 9        130258  variant_plus_rt        concurrent            2
 10       130258  variant_plus_rt        concurrent            2
 11       130258  variant_plus_rt        concurrent            2
 12       130262  variant_plus_rt        concurrent            2
 13       130262  variant_plus_rt        concurrent            2
 14       130262  variant_plus_rt        concurrent            2
 15       130262  variant_plus_rt        concurrent            2
 16       130262  variant_plus_rt        concurrent            2
 17       130262  variant_plus_rt        concurrent            2
 18       130269  variant_plus_rt        concurrent            2
 19       130269  variant_plus_rt        concurrent            2

                                         phase_summary
 0   systemic:systemic:concurrent:Carboplatin and C...
 1   systemic:systemic:concurrent:Carboplatin and C...
 2   systemic:systemic:concurrent:Carboplatin and C...
 3   systemic:systemic:concurrent:Carboplatin and C...
 4   systemic:systemic:concurrent:Carboplatin and C...
 5   systemic:systemic:concurrent:Carboplatin and C...
 6   systemic:systemic:concurrent:Carboplatin and D...
 7   systemic:systemic:concurrent:Carboplatin and D...
 8   systemic:systemic:concurrent:Carboplatin and D...
 9   systemic:systemic:concurrent:Carboplatin and D...
 10  systemic:systemic:concurrent:Carboplatin and D...
 11  systemic:systemic:concurrent:Carboplatin and D...
 12  systemic:systemic:concurrent:Carboplatin and D...
 13  systemic:systemic:concurrent:Carboplatin and D...
 14  systemic:systemic:concurrent:Carboplatin and D...
 15  systemic:systemic:concurrent:Carboplatin and D...
 16  systemic:systemic:concurrent:Carboplatin and D...
 17  systemic:systemic:concurrent:Carboplatin and D...
 18  systemic:systemic:concurrent:Carboplatin and D...
 19  systemic:systemic:concurrent:Carboplatin and D...  }

In [12]:
display_entry_run("sequential_crt_adjuvant_durvalumab")

## `sequential_crt_adjuvant_durvalumab` (bundle)

Assembled bundles: **2410**

### Phase counts

              phase_id  row_count
0             systemic        625
1         radiotherapy        506
2  adjuvant_durvalumab          4

### Bundle rows

,recipe_id,bundle_name,variant_cui,assembly_mode,sequence_template,phase_count,phase_summary
0,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
1,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
2,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
3,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
4,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
5,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
6,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
7,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
8,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
9,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
10,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
11,sequential_crt_adjuvant_durvalumab,Carboplatin and Cisplatin + External beam radi...,130256,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Cisplati...
12,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...
13,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...
14,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...
15,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...
16,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...
17,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...
18,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...
19,sequential_crt_adjuvant_durvalumab,Carboplatin and Docetaxel (DCb) + External bea...,130258,variant_plus_rt,sequential,3,systemic:systemic:pre:Carboplatin and Docetaxe...

### Phase examples: `systemic`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,130256,Variant #01,Carboplatin and Cisplatin,-3,False,True,False,False,1,1
1,130256,Variant #01,Carboplatin and Cisplatin,-2,False,True,False,False,1,1
2,130256,Variant #01,Carboplatin and Cisplatin,-1,False,True,False,False,1,1
3,130256,Variant #01,Carboplatin and Cisplatin,0,False,True,False,False,1,1
4,130256,Variant #01,Carboplatin and Cisplatin,1,False,True,False,False,1,1
5,130258,Variant #01,Carboplatin and Docetaxel (DCb),0,False,True,False,False,4,3
6,130258,Variant #01,Carboplatin and Docetaxel (DCb),1,False,True,False,False,4,3
7,130262,Variant #05,Carboplatin and Docetaxel (DCb),0,False,True,False,False,2,2
8,130262,Variant #05,Carboplatin and Docetaxel (DCb),1,False,True,False,False,2,2
9,130269,Variant #12,Carboplatin and Docetaxel (DCb),-1,False,True,False,False,4,1

### Phase examples: `radiotherapy`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,144918.0,Variant #01,ADT and RT,None,None,None,None,None,13,1
1,144919.0,Variant #02,ADT and RT,None,None,None,None,None,1,1
2,129928.0,Variant #01,Bevacizumab and RT,None,None,None,None,None,1,1
3,129951.0,Variant #01,Bicalutamide and RT,None,None,None,None,None,1,1
4,136628.0,Variant #01,"Bleomycin, Methotrexate, Vinblastine/RT",None,None,None,None,None,1,1
5,136631.0,Variant #01,"BuCyTBI, then allo HSCT",None,None,None,None,None,2,1
6,130207.0,Variant #01,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
7,130208.0,Variant #02,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
8,130209.0,Variant #03,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1
9,150915.0,Variant #04,Capecitabine and Cisplatin (CX) and RT,None,None,None,None,None,1,1

### Phase examples: `adjuvant_durvalumab`

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,131824,Variant #01,Durvalumab monotherapy,-1,False,True,False,False,7,1
1,131824,Variant #01,Durvalumab monotherapy,0,False,True,False,False,7,1
2,131824,Variant #01,Durvalumab monotherapy,1,False,True,False,False,7,1
3,161285,Variant #05,Durvalumab monotherapy,1,False,True,False,False,1,1

{'mode': 'bundle',
 'phase_counts':               phase_id  row_count
 0             systemic        625
 1         radiotherapy        506
 2  adjuvant_durvalumab          4,
 'phase_examples': {'systemic':    variant_cui      variant                          regimen  version  \
  0       130256  Variant #01        Carboplatin and Cisplatin       -3
  1       130256  Variant #01        Carboplatin and Cisplatin       -2
  2       130256  Variant #01        Carboplatin and Cisplatin       -1
  3       130256  Variant #01        Carboplatin and Cisplatin        0
  4       130256  Variant #01        Carboplatin and Cisplatin        1
  5       130258  Variant #01  Carboplatin and Docetaxel (DCb)        0
  6       130258  Variant #01  Carboplatin and Docetaxel (DCb)        1
  7       130262  Variant #05  Carboplatin and Docetaxel (DCb)        0
  8       130262  Variant #05  Carboplatin and Docetaxel (DCb)        1
  9       130269  Variant #12  Carboplatin and Docetaxel (DCb)       -1

     has_radiation_sig  has_non_radiation_sig  is_concurrent_chemort  \
  0              False                   True                  False
  1              False                   True                  False
  2              False                   True                  False
  3              False                   True                  False
  4              False                   True                  False
  5              False                   True                  False
  6              False                   True                  False
  7              False                   True                  False
  8              False                   True                  False
  9              False                   True                  False

     is_rt_only  study_count  condition_count
  0       False            1                1
  1       False            1                1
  2       False            1                1
  3       False            1                1
  4       False            1                1
  5       False            4                3
  6       False            4                3
  7       False            2                2
  8       False            2                2
  9       False            4                1  ,
  'radiotherapy':    variant_cui      variant                                  regimen version  \
  0     144918.0  Variant #01                               ADT and RT    None
  1     144919.0  Variant #02                               ADT and RT    None
  2     129928.0  Variant #01                       Bevacizumab and RT    None
  3     129951.0  Variant #01                      Bicalutamide and RT    None
  4     136628.0  Variant #01  Bleomycin, Methotrexate, Vinblastine/RT    None
  5     136631.0  Variant #01                  BuCyTBI, then allo HSCT    None
  6     130207.0  Variant #01   Capecitabine and Cisplatin (CX) and RT    None
  7     130208.0  Variant #02   Capecitabine and Cisplatin (CX) and RT    None
  8     130209.0  Variant #03   Capecitabine and Cisplatin (CX) and RT    None
  9     150915.0  Variant #04   Capecitabine and Cisplatin (CX) and RT    None

    has_radiation_sig has_non_radiation_sig is_concurrent_chemort is_rt_only  \
  0              None                  None                  None       None
  1              None                  None                  None       None
  2              None                  None                  None       None
  3              None                  None                  None       None
  4              None                  None                  None       None
  5              None                  None                  None       None
  6              None                  None                  None       None
  7              None                  None                  None       None
  8              None                  None                  None       None
  9              None                  None                  None       None

     study_count  condition_count
  0           13                1
  1            1                1
  2            1                1
  3            1                1
  4            1                1
  5            2                1
  6            1                1
  7            1                1
  8            1                1
  9            1                1  ,
  'adjuvant_durvalumab':    variant_cui      variant                 regimen  version  \
  0       131824  Variant #01  Durvalumab monotherapy       -1
  1       131824  Variant #01  Durvalumab monotherapy        0
  2       131824  Variant #01  Durvalumab monotherapy        1
  3       161285  Variant #05  Durvalumab monotherapy        1

     has_radiation_sig  has_non_radiation_sig  is_concurrent_chemort  \
  0              False                   True                  False
  1              False                   True                  False
  2              False                   True                  False
  3              False                   True                  False

     is_rt_only  study_count  condition_count
  0       False            7                1
  1       False            7                1
  2       False            7                1
  3       False            1                1  },
 'bundle_count': 2410,
 'bundle_rows':                              recipe_id  \
 0   sequential_crt_adjuvant_durvalumab
 1   sequential_crt_adjuvant_durvalumab
 2   sequential_crt_adjuvant_durvalumab
 3   sequential_crt_adjuvant_durvalumab
 4   sequential_crt_adjuvant_durvalumab
 5   sequential_crt_adjuvant_durvalumab
 6   sequential_crt_adjuvant_durvalumab
 7   sequential_crt_adjuvant_durvalumab
 8   sequential_crt_adjuvant_durvalumab
 9   sequential_crt_adjuvant_durvalumab
 10  sequential_crt_adjuvant_durvalumab
 11  sequential_crt_adjuvant_durvalumab
 12  sequential_crt_adjuvant_durvalumab
 13  sequential_crt_adjuvant_durvalumab
 14  sequential_crt_adjuvant_durvalumab
 15  sequential_crt_adjuvant_durvalumab
 16  sequential_crt_adjuvant_durvalumab
 17  sequential_crt_adjuvant_durvalumab
 18  sequential_crt_adjuvant_durvalumab
 19  sequential_crt_adjuvant_durvalumab

                                           bundle_name  variant_cui  \
 0   Carboplatin and Cisplatin + External beam radi...       130256
 1   Carboplatin and Cisplatin + External beam radi...       130256
 2   Carboplatin and Cisplatin + External beam radi...       130256
 3   Carboplatin and Cisplatin + External beam radi...       130256
 4   Carboplatin and Cisplatin + External beam radi...       130256
 5   Carboplatin and Cisplatin + External beam radi...       130256
 6   Carboplatin and Cisplatin + External beam radi...       130256
 7   Carboplatin and Cisplatin + External beam radi...       130256
 8   Carboplatin and Cisplatin + External beam radi...       130256
 9   Carboplatin and Cisplatin + External beam radi...       130256
 10  Carboplatin and Cisplatin + External beam radi...       130256
 11  Carboplatin and Cisplatin + External beam radi...       130256
 12  Carboplatin and Docetaxel (DCb) + External bea...       130258
 13  Carboplatin and Docetaxel (DCb) + External bea...       130258
 14  Carboplatin and Docetaxel (DCb) + External bea...       130258
 15  Carboplatin and Docetaxel (DCb) + External bea...       130258
 16  Carboplatin and Docetaxel (DCb) + External bea...       130258
 17  Carboplatin and Docetaxel (DCb) + External bea...       130258
 18  Carboplatin and Docetaxel (DCb) + External bea...       130258
 19  Carboplatin and Docetaxel (DCb) + External bea...       130258

       assembly_mode sequence_template  phase_count  \
 0   variant_plus_rt        sequential            3
 1   variant_plus_rt        sequential            3
 2   variant_plus_rt        sequential            3
 3   variant_plus_rt        sequential            3
 4   variant_plus_rt        sequential            3
 5   variant_plus_rt        sequential            3
 6   variant_plus_rt        sequential            3
 7   variant_plus_rt        sequential            3
 8   variant_plus_rt        sequential            3
 9   variant_plus_rt        sequential            3
 10  variant_plus_rt        sequential            3
 11  variant_plus_rt        sequential            3
 12  variant_plus_rt        sequential            3
 13  variant_plus_rt        sequential            3
 14  variant_plus_rt        sequential            3
 15  variant_plus_rt        sequential            3
 16  variant_plus_rt        sequential            3
 17  variant_plus_rt        sequential            3
 18  variant_plus_rt        sequential            3
 19  variant_plus_rt        sequential            3

                                         phase_summary
 0   systemic:systemic:pre:Carboplatin and Cisplati...
 1   systemic:systemic:pre:Carboplatin and Cisplati...
 2   systemic:systemic:pre:Carboplatin and Cisplati...
 3   systemic:systemic:pre:Carboplatin and Cisplati...
 4   systemic:systemic:pre:Carboplatin and Cisplati...
 5   systemic:systemic:pre:Carboplatin and Cisplati...
 6   systemic:systemic:pre:Carboplatin and Cisplati...
 7   systemic:systemic:pre:Carboplatin and Cisplati...
 8   systemic:systemic:pre:Carboplatin and Cisplati...
 9   systemic:systemic:pre:Carboplatin and Cisplati...
 10  systemic:systemic:pre:Carboplatin and Cisplati...
 11  systemic:systemic:pre:Carboplatin and Cisplati...
 12  systemic:systemic:pre:Carboplatin and Docetaxe...
 13  systemic:systemic:pre:Carboplatin and Docetaxe...
 14  systemic:systemic:pre:Carboplatin and Docetaxe...
 15  systemic:systemic:pre:Carboplatin and Docetaxe...
 16  systemic:systemic:pre:Carboplatin and Docetaxe...
 17  systemic:systemic:pre:Carboplatin and Docetaxe...
 18  systemic:systemic:pre:Carboplatin and Docetaxe...
 19  systemic:systemic:pre:Carboplatin and Docetaxe...  }

In [13]:
display_entry_run("egfr_intervention")

## `egfr_intervention` (variant)

Matched variants: **104**

,variant_cui,variant,regimen,version,has_radiation_sig,has_non_radiation_sig,is_concurrent_chemort,is_rt_only,study_count,condition_count
0,129625,Variant #01,Afatinib and Bevacizumab,-1,False,True,False,False,1,1
1,129625,Variant #01,Afatinib and Bevacizumab,0,False,True,False,False,1,1
2,129625,Variant #01,Afatinib and Bevacizumab,1,False,True,False,False,1,1
3,129626,Variant #01,Afatinib and Cetuximab,-1,False,True,False,False,1,1
4,129626,Variant #01,Afatinib and Cetuximab,0,False,True,False,False,1,1
5,129626,Variant #01,Afatinib and Cetuximab,1,False,True,False,False,1,1
6,129627,Variant #01,Afatinib and Paclitaxel,-1,False,True,False,False,1,1
7,129627,Variant #01,Afatinib and Paclitaxel,0,False,True,False,False,1,1
8,129627,Variant #01,Afatinib and Paclitaxel,1,False,True,False,False,1,1
9,129628,Variant #01,Afatinib monotherapy,-1,False,True,False,False,4,3
10,129628,Variant #01,Afatinib monotherapy,0,False,True,False,False,4,3
11,129628,Variant #01,Afatinib monotherapy,1,False,True,False,False,4,3
12,129629,Variant #02,Afatinib monotherapy,-3,False,True,False,False,4,1
13,129629,Variant #02,Afatinib monotherapy,-2,False,True,False,False,4,1
14,129629,Variant #02,Afatinib monotherapy,-1,False,True,False,False,4,1
15,129629,Variant #02,Afatinib monotherapy,0,False,True,False,False,4,1
16,129629,Variant #02,Afatinib monotherapy,1,False,True,False,False,4,1
17,129631,Variant #04,Afatinib monotherapy,-3,False,True,False,False,2,1
18,129631,Variant #04,Afatinib monotherapy,-2,False,True,False,False,2,1
19,129631,Variant #04,Afatinib monotherapy,-1,False,True,False,False,2,1

{'mode': 'variant',
 'row_count': 104,
 'rows':     variant_cui      variant                   regimen  version  \
 0        129625  Variant #01  Afatinib and Bevacizumab       -1
 1        129625  Variant #01  Afatinib and Bevacizumab        0
 2        129625  Variant #01  Afatinib and Bevacizumab        1
 3        129626  Variant #01    Afatinib and Cetuximab       -1
 4        129626  Variant #01    Afatinib and Cetuximab        0
 5        129626  Variant #01    Afatinib and Cetuximab        1
 6        129627  Variant #01   Afatinib and Paclitaxel       -1
 7        129627  Variant #01   Afatinib and Paclitaxel        0
 8        129627  Variant #01   Afatinib and Paclitaxel        1
 9        129628  Variant #01      Afatinib monotherapy       -1
 10       129628  Variant #01      Afatinib monotherapy        0
 11       129628  Variant #01      Afatinib monotherapy        1
 12       129629  Variant #02      Afatinib monotherapy       -3
 13       129629  Variant #02      Afatinib monotherapy       -2
 14       129629  Variant #02      Afatinib monotherapy       -1
 15       129629  Variant #02      Afatinib monotherapy        0
 16       129629  Variant #02      Afatinib monotherapy        1
 17       129631  Variant #04      Afatinib monotherapy       -3
 18       129631  Variant #04      Afatinib monotherapy       -2
 19       129631  Variant #04      Afatinib monotherapy       -1

     has_radiation_sig  has_non_radiation_sig  is_concurrent_chemort  \
 0               False                   True                  False
 1               False                   True                  False
 2               False                   True                  False
 3               False                   True                  False
 4               False                   True                  False
 5               False                   True                  False
 6               False                   True                  False
 7               False                   True                  False
 8               False                   True                  False
 9               False                   True                  False
 10              False                   True                  False
 11              False                   True                  False
 12              False                   True                  False
 13              False                   True                  False
 14              False                   True                  False
 15              False                   True                  False
 16              False                   True                  False
 17              False                   True                  False
 18              False                   True                  False
 19              False                   True                  False

     is_rt_only  study_count  condition_count
 0        False            1                1
 1        False            1                1
 2        False            1                1
 3        False            1                1
 4        False            1                1
 5        False            1                1
 6        False            1                1
 7        False            1                1
 8        False            1                1
 9        False            4                3
 10       False            4                3
 11       False            4                3
 12       False            4                1
 13       False            4                1
 14       False            4                1
 15       False            4                1
 16       False            4                1
 17       False            2                1
 18       False            2                1
 19       False            2                1  }